<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="0" skipped="2" tests="14" time="5.206" timestamp="2023-12-03T11:57:54.512676" hostname="AsusROGStrix"><testcase classname="tests.test_circle.TestCircle" name="test_area" file="tests\test_circle.py" line="20" time="0.002"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------
Setting up &lt;bound method TestCircle.test_area of &lt;test_circle.TestCircle object at 0x000001F3DC7DB810&gt;&gt;
Tearing down &lt;bound method TestCircle.test_area of &lt;test_circle.TestCircle object at 0x000001F3DC7DB810&gt;&gt;

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_circle.TestCircle" name="test_not_same_area_rectangle" file="tests\test_circle.py" line="28" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------
Setting up &lt;bound method TestCircle.test_not_same_area_rectangle of &lt;test_circle.TestCircle object at 0x000001F3DC7EC750&gt;&gt;
Tearing down &lt;bound method TestCircle.test_not_same_area_rectangle of &lt;test_circle.TestCircle object at 0x000001F3DC7EC750&gt;&gt;

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_circle.TestCircle" name="test_one" file="tests\test_circle.py" line="14" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------
Setting up &lt;bound method TestCircle.test_one of &lt;test_circle.TestCircle object at 0x000001F3DC7DAB50&gt;&gt;
Tearing down &lt;bound method TestCircle.test_one of &lt;test_circle.TestCircle object at 0x000001F3DC7DAB50&gt;&gt;

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_circle.TestCircle" name="test_perimeter" file="tests\test_circle.py" line="23" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------
Setting up &lt;bound method TestCircle.test_perimeter of &lt;test_circle.TestCircle object at 0x000001F3DC7DBF90&gt;&gt;
Tearing down &lt;bound method TestCircle.test_perimeter of &lt;test_circle.TestCircle object at 0x000001F3DC7DBF90&gt;&gt;

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_circle.TestCircle" name="test_two" file="tests\test_circle.py" line="17" time="0.002"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------
Setting up &lt;bound method TestCircle.test_two of &lt;test_circle.TestCircle object at 0x000001F3DC7DB110&gt;&gt;
Tearing down &lt;bound method TestCircle.test_two of &lt;test_circle.TestCircle object at 0x000001F3DC7DB110&gt;&gt;

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_my_functions" name="test_add" file="tests\test_my_functions.py" line="26" time="0.001"><skipped type="pytest.skip" message="This feature is currently broken">C:\Users\Pawe≈Ç Galus\source\repos\PytestTutorial\tests\test_my_functions.py:27: This feature is currently broken</skipped><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_my_functions" name="test_add_strings" file="tests\test_my_functions.py" line="8" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_my_functions" name="test_divide" file="tests\test_my_functions.py" line="12" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_my_functions" name="test_divide_by_zero" file="tests\test_my_functions.py" line="16" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_my_functions" name="test_divide_zero_broken" file="tests\test_my_functions.py" line="30" time="0.001"><skipped type="pytest.xfail" message="We know we cannot divide by zero" /><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_my_functions" name="test_very_slow" file="tests\test_my_functions.py" line="20" time="5.002"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_rectangle" name="test_area" file="tests\test_rectangle.py" line="3" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_rectangle" name="test_not_equal" file="tests\test_rectangle.py" line="9" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_rectangle" name="test_perimeter" file="tests\test_rectangle.py" line="6" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase></testsuite></testsuites>